### ISSUE TITLE
Service Worker?

### ISSUE THREAD

**Issue by stroop566** [caisiduo/hexo-theme-lightime#1]
1.你好，请问博客上使用Service Worker有什么用，为什么会和InstantClick冲突？
2.建议配置文件设置js等的目录，方便cdn，进一步加快博客速度。
https://github.com/tufu9441/maupassant-hexo/pull/50

**Comment by caisiduo** [comment]
sw和instant click冲突一直都是 所以我默认只开一个 可以自己选择
js和css我都放在对应位置 改起来应该没那么麻烦

**Comment by caisiduo** [comment]
https://github.com/caisiduo/hexo-theme-lightime/commit/5bc1d3227eed013bf6adca10e1d6734e07249dc6
完成了，有bug还请告知。用了不是很妥当的写法。
